[package]
name = "fluree-graph-json-ld"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Minimal JSON-LD processing library"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
fluree-graph-ir = { path = "../fluree-graph-ir" }
fluree-vocab = { path = "../fluree-vocab" }

[dev-dependencies]
pretty_assertions = "1.4"
