[package]
name = "fluree-graph-turtle"
description = "Turtle (TTL) parser for Fluree graph"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fluree-graph-ir = { path = "../fluree-graph-ir" }
fluree-vocab = { path = "../fluree-vocab" }
winnow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
